### PR TITLE
feat(generators): Pass back result from provider state setup URL #53

### PR DESCRIPTION
**Pull request by slt**
Addressing issue https://github.com/pact-foundation/pact-provider-verifier/issues/49

* Adds support for all generators from v3 spec and the ProviderState generator.
* ProviderState generator saves the results from the --provider-state-setup-url and templates them into a value using an expression.

Requires https://github.com/pact-foundation/pact-ruby/pull/273 & https://github.com/pact-foundation/pact-support/pull/97

I based this around @hhhonzik's previous pull request [here ](https://github.com/pact-foundation/pact-provider-verifier/pull/53)

### CODE REVIEW

**Comment by livecodelife** [comment]
Is this slated to be added soon? It would be very useful!

**Comment by slt** [comment]
I ended up moving to the rust standalone provider verifier, it has all of these features implemented already as well as the v3 and v4 pact specifications

https://docs.pact.io/implementation_guides/rust/pact_verifier_cli

Given its standalone and almost a drop-in replacement, I don't see why it wouldn't be preferred over this one.  I would suggest that the docs of this project are updated to point to it instead.

I'm not a ruby developer and I only did these pull requests to unblock myself, I'm happy for them to be merged if they help anyone else but I don't have the capacity to support this work moving forward

**Comment by YOU54F** [comment]
Hey thanks @slt sorry for the delay in looking at this.

You are correct, the rust is the preferred going forward and this is considered to be legacy

https://docs.pact.io/implementation_guides/cli#provider-verifier

thanks for your support and work in pact-ruby as well, especially as a non ruby developer (it is how I started with Pact)

Beth hasn't had a-lot of bandwidth for looking at these PR's and as we can utilise the FFI library in Ruby, we may go down that route for v3/v4 support but not decided yet. Great that you found the rust library and that will sort you out!

There is probably value in keeping the PR, however if you want to close it we can always re-open it in the future.

**Comment by YOU54F** [comment]
closing in favour of #125

**Pull request closed without merging**
