### PR TITLE
Remove need for provider-states-url by dynamically calling the set up…

### PR DESCRIPTION
**Pull request by bethesque**
… code during test execution

### CODE REVIEW

**Comment by neilcampbell** [comment]
Not directly related to this PR, however is there a teardown invocation of the provider-states-url ?

**Comment by bethesque** [comment]
There could be, but I don't think any of the other implementations have used one. I believe the set up is assumed to clear the state from before it. @uglyog can confirm with the JVM?

**Comment by uglyog** [comment]
Not sure what you want me to confirm? That the JVM implementation has a similar mechanism, or that it requires this functionality?

**Comment by neilcampbell** [comment]
@uglyog Does it have a teardown mechanism currently? Or do you assuming that state is cleared during set up.

**Comment by uglyog** [comment]
It has a teardown, which is optional. The basic use is setup only. See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle#teardown-calls-for-state-changes-version-325247 

Just checking the JUnit implementation, and it looks like it only supports setup, no teardown.

So the basic answer is the JVM does have a state teardown call, but only if validation is run from Gradle or Maven and it is not enabled by default.

**Comment by mefellows** [comment]
This is so much better now!

I'll pull this in as is, and test it out with the `Go/ JS` libraries later today.

As for the 30x, we can always patch after.

**Pull request merged**
